---
title: "Combining Passive Sensing and Self-Reported Symptoms with Network Analysis to Predict Suicidal Ideation in Medical Residents"
output: github_document
---
## Setup
```{r setup, include=FALSE, echo=FALSE}
# Set working directory
# Please update this to your directory as needed
dir <- "/Users/thaliaviranda/Documents/GitHub/PassiveSensing-Symptoms-NetworkAnalysis"
setwd(dir)

# load packages
# Define a vector of package names
packages <- c("dplyr", "tidyverse", "ggplot2", "rstatix", "tableone", "lsr")  
for (pkg in packages) {
if (!require(pkg, character.only = TRUE)){
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
    }
}

```

```{r data_cleaning, include=FALSE, echo=FALSE}
#====================================================================
# Load Data
#====================================================================
# self report: 2018 and 20919 baseline 
selfreport_2018_2019 <- read.csv(paste0(dir, "/data/", "IHSdata_20182019_03062024.csv"), header = TRUE)

length(colnames(selfreport_2018_2019))
colnames(selfreport_2018_2019)

# 2018: sensor (activity and sleep), self-report: baseline, Q1Q2, Q3, Q4
c2018_step_sleep_mood_daily_BL <- read.csv(paste0(dir, "/data/2018/", "US_step_sleep_mood_daily_2018cohort_BL.csv"), header = TRUE)
c2018_step_sleep_mood_daily_Q1Q2 <- read.csv(paste0(dir, "/data/2018/", "US_step_sleep_mood_daily_2018cohort_Q1Q2.csv"), header = TRUE)
c2018_step_sleep_mood_daily_Q3 <- read.csv(paste0(dir, "/data/2018/", "US_step_sleep_mood_daily_2018cohort_Q3.csv"), header = TRUE)
c2018_step_sleep_mood_daily_Q4 <- read.csv(paste0(dir, "/data/2018/", "US_step_sleep_mood_daily_2018cohort_Q4.csv"), header = TRUE)


# 2019: sensor (activity and sleep), self-report: baseline, Q1Q2, Q3, Q4
c2019_step_sleep_mood_daily_BLQ1 <- read.csv(paste0(dir, "/data/2019/", "Step_sleep_mood_daily_2019_BLQ1.csv"), header = TRUE)
c2019_step_sleep_mood_daily_Q2 <- read.csv(paste0(dir, "/data/2019/", "Step_sleep_mood_daily_2019_Q2.csv"), header = TRUE)
c2019_step_sleep_mood_daily_Q3 <- read.csv(paste0(dir, "/data/2019/", "Step_sleep_mood_daily_2019_Q3.csv"), header = TRUE)
c2019_step_sleep_mood_daily_Q4 <- read.csv(paste0(dir, "/data/2019/", "Step_sleep_mood_daily_2019_Q4.csv"), header = TRUE)


#====================================================================
# Data Cleaning & Preprocessing
#====================================================================
# ------ self-report and data ------
# colnames(selfreport_2018_2019)
# Check number of UserID of those who answered "Yes" (1) to Q1 of C-SSRS questionnaire: 
# "Have you wished you were dead or wished you could go to sleep and not wake up?"
#  thought of killing themselves (as indicated by ssrs_wish = 1 (Yes); 2 (No)) at ANY quarter
# ssrs_wish1 = Q1, ssrs_wish2 = Q2, ssrs_wish3 = Q3, ssrs_wish4 = Q4
# NA/Invalid number = missing data, exclude that quarter
ssrs_wish <- selfreport_2018_2019 %>%
  # filter(Year == 2019) %>%
  select(UserID, Year, starts_with("ssrs_wish"), -ssrs_wish0) %>%
  filter(ssrs_wish1 == 1 | ssrs_wish2 == 1 | ssrs_wish3 == 1 | ssrs_wish4 == 1) 
# summary
ssrs_wish_summ <- ssrs_wish %>%
  gather(key, value, -UserID, -Year) %>% 
  mutate(wish_dead = ifelse(value == 1, "Yes", "No")) %>% # NA means missing data, i.e., they did not complete quarterly measure
  group_by(Year, key, wish_dead) %>%
  summarise(n=n())  %>% 
  arrange(wish_dead)

# get self-report data (this is combining 2018 and 2019)
selfreport_wish <- selfreport_2018_2019 %>%
  # filter(Year == 2018) %>%
  filter(ssrs_wish1 == 1 | ssrs_wish2 == 1 | ssrs_wish3 == 1 | ssrs_wish4 == 1) %>%
  select(UserID, Year, starts_with("ssrs_kill"), Age, Sex, Marital, Child, SigOther0, Ethnicity, starts_with("rotation"), starts_with("hours"), starts_with("daysoff"), starts_with("error"), Neu0, EFE0, depr0, deprTreat0, starts_with("specTreat"), starts_with("PHQtot"), starts_with("PHQ10above"), starts_with("SLE"), starts_with("ssrs")) 

#export csv
write.csv(as.data.frame(selfreport_wish), paste0(dir, "/data/clean_data/", "selfreport_wish", ".csv"))
  
# Check number of UserID of those who answered "Yes" (1) to Q2 of C-SSRS questionnaire: 
# "Have you actually had any thoughts about killing yourself?"
#  thought of killing themselves (as indicated by ssrs_wish = 1 (Yes); 2 (No)) at ANY quarter
# ssrs_kill1 = Q1, ssrs_kill2 = Q2, ssrs_kill3 = Q3, ssrs_kill4 = Q4
# NA/Invalid number = missing data, exclude that quarter
ssrs_kill <- selfreport_2018_2019 %>%
  filter(Year == 2018) %>%
  select(UserID, Year, starts_with("ssrs_kill"),-ssrs_kill0) %>%
  filter(ssrs_kill1 == 1 | ssrs_kill2 == 1 | ssrs_kill3 == 1 | ssrs_kill4 == 1) 
 
# summary
ssrs_kill_summ <- ssrs_kill%>%
  gather(key, value, -UserID, -Year) %>% 
  mutate(thought_killing = ifelse(value == 1, "Yes", "No"))%>% # NA means missing data, i.e., they did not complete quarterly measure
  group_by(Year, key, thought_killing) %>%
  summarise(n=n())  %>% 
  arrange(thought_killing)

# get self-report data (this is combining 2018 and 2019)
selfreport_kill <- selfreport_2018_2019 %>%
  # filter(Year == 2018) %>%
  filter(ssrs_kill1 == 1 | ssrs_kill2 == 1 | ssrs_kill3 == 1 | ssrs_kill4 == 1) %>%
  select(UserID, Year, starts_with("ssrs_kill"), Age, Sex, Marital, Child, SigOther0, Ethnicity, starts_with("rotation"), starts_with("hours"), starts_with("daysoff"), starts_with("error"), Neu0, EFE0, depr0, deprTreat0, starts_with("specTreat"), starts_with("PHQtot"), starts_with("PHQ10above"), starts_with("SLE"), starts_with("ssrs")) 

# export csv
write.csv(as.data.frame(selfreport_kill), paste0(dir, "/data/clean_data/", "selfreport_kill", ".csv"))

# check if people in ssrs_kill is a subset of people in ssrs_wish
wish_ids <- unique(ssrs_wish$participant_id)
kill_ids <- unique(ssrs_kill$participant_id)

# Check if all participants in `wide_data` are in `long_data`
is_subset <- all(kill_ids %in% wish_ids)
if (is_subset) {
  print("All participants in the ssrs_kill dataset are in the ssrs_wish dataset.")
} else {
  print("Not all participants in the ssrs_kill dataset are in the ssrs_wish dataset.")
}

# only using ssrs variables from 1-4
# do not include variables that aren not available for cohort in bot years 

# ------ daily sensor data ------
# baseline
c2018_step_sleep_mood_daily_BL$METRIC_START_DATE <- as.Date(c2018_step_sleep_mood_daily_BL$METRIC_START_DATE, format = "%d-%b-%y")
c2018_daily_BL <- c2018_step_sleep_mood_daily_BL %>%
  rename(UserID = STUDY_PRTCPT_ID, 
          step = STEP_COUNT, 
          sleep = SLEEP_COUNT,
          mood = MOOD, 
          date = METRIC_START_DATE) %>% 
  mutate(quarter = "BL") %>%
  select(-METRIC_END_DATE, -STUDY_ID)

# Q1 and Q2
# need to know the cut off of the Q1 (Jul, Aug, Sep) and Q2 (Oct, Nov, Dec)
# class(c2018_step_sleep_mood_daily_Q1Q2$METRIC_START_DATE)
c2018_step_sleep_mood_daily_Q1Q2$METRIC_START_DATE <- as.Date(c2018_step_sleep_mood_daily_Q1Q2$METRIC_START_DATE, format = "%d-%b-%y")

c2018_daily_Q1Q2 <- c2018_step_sleep_mood_daily_Q1Q2 %>%
  rename(UserID = STUDY_PRTCPT_ID, 
          step = STEP_COUNT, 
          sleep = SLEEP_COUNT,
          mood = MOOD, 
          date = METRIC_START_DATE) %>% 
  mutate(month_start = format(date, "%b"), 
          quarter = ifelse(month_start %in% c("Jul", "Aug", "Sep"), "Q1", "Q2")) %>%
  select(-METRIC_END_DATE, -STUDY_ID, -month_start) 

# Q3
c2018_step_sleep_mood_daily_Q3$METRIC_START_DATE <- as.Date(c2018_step_sleep_mood_daily_Q3$METRIC_START_DATE, format = "%d-%b-%y")
c2018_daily_Q3 <- c2018_step_sleep_mood_daily_Q3 %>%
  rename(UserID = STUDY_PRTCPT_ID, 
          step = STEP_COUNT, 
          sleep = SLEEP_COUNT,
          mood = MOOD, 
          date = METRIC_START_DATE) %>% 
  mutate(quarter = "Q3") %>%
  select(-METRIC_END_DATE, -STUDY_ID)

# Q4
c2018_step_sleep_mood_daily_Q4$METRIC_START_DATE <- as.Date(c2018_step_sleep_mood_daily_Q4$METRIC_START_DATE, format = "%d-%b-%y")
c2018_daily_Q4 <- c2018_step_sleep_mood_daily_Q4 %>%
  rename(UserID = STUDY_PRTCPT_ID, 
          step = STEP_COUNT, 
          sleep = SLEEP_COUNT,
          mood = MOOD, 
          date = METRIC_START_DATE) %>% 
  mutate(quarter = "Q4")%>%
  select(-METRIC_END_DATE, -STUDY_ID)

# 2018 - LONG DATA: rbind *daily* 2018 datasets
c2018_BL_Q1_Q2_Q3_Q4 <- rbind(c2018_daily_BL, c2018_daily_Q1Q2, c2018_daily_Q3, c2018_daily_Q4) %>% 
  arrange(UserID, quarter) %>%
  mutate(Year = 2018) # add year label; so we can differentiate after rbinding participants from 2018 and 2019 datasets

# 2019 datasets are clean! :) it has the same structure/format as the 2018 dataset I created above
c2019_BL_Q1_Q2_Q3_Q4 <- rbind(c2019_step_sleep_mood_daily_BLQ1, c2019_step_sleep_mood_daily_Q2, c2019_step_sleep_mood_daily_Q3, c2019_step_sleep_mood_daily_Q4) %>% 
  arrange(UserID, quarter)%>%
  mutate(Year = 2019) # add year label; so we can differentiate after rbinding participants from 2018 and 2019 datasets

# Rbind both 2018 and 2019 sensor dataset
sensor_2018_2019_BL_Q1_Q2_Q3_Q4 <- rbind(c2018_BL_Q1_Q2_Q3_Q4, c2019_BL_Q1_Q2_Q3_Q4)


# ACTIVE  MINUTES: 
c2018_active <- read.csv(paste0(dir, "/data/2018/", "All_Active_Minutes_2018.csv"), header = TRUE)
class(c2018_active$date)
c2018_active$date <- as.Date(c2018_active$date)
c2018_active <- c2018_active %>%
  mutate(Year = 2018, 
        month = format(date, '%b'),
        quarter = case_when(
      month %in% c("Jan", "Feb", "Mar") ~ "Q3",
      month %in% c("Apr", "May", "Jun") ~ "Q4",
      month %in% c("Jul", "Aug", "Sep") ~ "Q1",
      month %in% c("Oct", "Nov", "Dec") ~ "Q2",
    TRUE ~ NA_character_  # Handles unexpected values
  )) %>% 
  select(-month)

# 2019 ACTIVE MINUTES
c2019_active <- read.csv(paste0(dir, "/data/2019/", "ActiveMinutes_2019_daily_all.csv"), header = TRUE)
class(c2019_active$date)
c2019_active$date <- as.Date(c2019_active$date)
c2019_active <- c2019_active %>%
  mutate(Year = 2019, 
        month = format(date, '%b'),
        quarter = case_when(
      month %in% c("Jan", "Feb", "Mar") ~ "Q3",
      month %in% c("Apr", "May", "Jun") ~ "Q4",
      month %in% c("Jul", "Aug", "Sep") ~ "Q1",
      month %in% c("Oct", "Nov", "Dec") ~ "Q2",
    TRUE ~ NA_character_  # Handles unexpected values
  )) %>% 
  select(-month)

c2018_2019_active <- rbind(c2018_active, c2019_active)

# export clean data 
# first, get IDs for filtering sensor data 
ssrs_wish_ids <- selfreport_wish$UserID
ssrs_kill_ids <- selfreport_kill$UserID

# ------ sensor data: ssrs_wish yes only ------
# filtered sensor data (only including subjects with suicide wish or thought of killing themselves 
clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 <- sensor_2018_2019_BL_Q1_Q2_Q3_Q4%>%
  filter(UserID %in% ssrs_wish_ids)

# check n in the resulting dataset
unique_count <- clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 %>%
  summarise(unique_users = n_distinct(UserID)) %>%
  pull(unique_users)

print(unique_count)

# merge sensor + active min data
clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4$date <- as.Date(clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4$date)
clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 <- merge(
  clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4, 
  c2018_2019_active, 
  by = c("UserID", "date", "Year", "quarter"), 
  all.x = TRUE, 
  all.y = FALSE
)

# check n in the resulting dataset
unique_count <- clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 %>%
  summarise(unique_users = n_distinct(UserID)) %>%
  pull(unique_users)

print(unique_count)

# write.csv(as.data.frame(clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4), paste0(dir, "/data/clean_data/", "clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4", ".csv"))

# summary per quarter
clean_sensor_all <- clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 %>%
  filter(!quarter == "BL") %>% # exclude BL data
  mutate(remove_nosensor = ifelse(step == 0 & sleep == 0, "Yes", "No")) %>% 
  filter(remove_nosensor == "No") %>%
  gather(key, value, -UserID, -quarter, -Year, -remove_nosensor,  -date) %>% 
  group_by(UserID, Year, quarter, key) %>% 
  summarize(n_sensordays = n(),
            mean = round(mean(value, na.rm=TRUE), digits = 1),
            sd = round(sd(value, na.rm=TRUE), digits = 1), 
            se = round(sd(value, na.rm=TRUE)/sqrt(length(value)), digits = 1), 
            median = round(median(value, na.rm=TRUE), digits = 1), 
            IQR = round(IQR(value, na.rm=TRUE), digits = 1))

summary(clean_sensor_all$n_sensordays[clean_sensor_all$quarter=="Q1" & clean_sensor_all$Year=="2018"])
summary(clean_sensor_all$n_sensordays[clean_sensor_all$quarter=="Q2"])
summary(clean_sensor_all$n_sensordays[clean_sensor_all$quarter=="Q3"])
summary(clean_sensor_all$n_sensordays[clean_sensor_all$quarter=="Q4"])

# check the distribution of number of days of sensor data among participant for each quarter 
# facet wrap 
hist_sensordays <- ggplot(clean_sensor_all, aes(x = n_sensordays)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~quarter*Year, ncol = 2) +
  theme_minimal() +
  labs(
    title = "Histogram with Facet Wrap",
    x = "Value",
    y = "Frequency"
  )
hist_sensordays

boxplot_sensordays <- ggplot(clean_sensor_all, aes(y = n_sensordays)) +
  geom_boxplot(fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~quarter*Year, ncol = 2) +
  theme_minimal() +
  labs(
    title = "Boxpolot with Facet Wrap"
  )
boxplot_sensordays

# --- sensor data: all participants ---
# merge sensor + active min data
all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 <- sensor_2018_2019_BL_Q1_Q2_Q3_Q4
all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4$date <- as.Date(sensor_2018_2019_BL_Q1_Q2_Q3_Q4$date)

all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 <- merge(
  all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4, 
  c2018_2019_active, 
  by = c("UserID", "date", "Year", "quarter"), 
  all.x = TRUE, 
  all.y = FALSE
)

all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4$quarter

# summary per quarter
sensor_all <- all_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 %>%
  mutate(quarter = as.factor(case_when(
        quarter %in% "Q3" ~ "3",
        quarter %in% "Q4" ~ "4",
        quarter %in% "Q1" ~ "1",
        quarter %in% "Q2" ~ "2",
      TRUE ~ NA_character_  # Handles unexpected values
    ))) %>% 
  filter(!quarter == "BL") %>% # exclude BL data
  mutate(remove_nosensor = ifelse(step == 0 & sleep == 0, "Yes", "No")) %>% 
  filter(remove_nosensor == "No") %>%
  gather(key, value, -UserID, -quarter, -Year, -remove_nosensor,  -date) %>% 
  group_by(UserID, Year, quarter, key) %>% 
  summarize(n_sensordays = n(),
            mean = round(mean(value, na.rm=TRUE), digits = 1),
            sd = round(sd(value, na.rm=TRUE), digits = 1), 
            se = round(sd(value, na.rm=TRUE)/sqrt(length(value)), digits = 1), 
            median = round(median(value, na.rm=TRUE), digits = 1), 
            IQR = round(IQR(value, na.rm=TRUE), digits = 1))

summary(sensor_all$n_sensordays[sensor_all$quarter==1 & sensor_all$Year=="2018"])
summary(sensor_all$n_sensordays[sensor_all$quarter==2])
summary(sensor_all$n_sensordays[sensor_all$quarter==3])
summary(sensor_all$n_sensordays[sensor_all$quarter==4])


# check the distribution of number of days of sensor data among participant for each quarter 
# facet wrap 
hist_sensordays <- ggplot(sensor_all, aes(x = n_sensordays)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~quarter*Year, ncol = 2) +
  theme_minimal() +
  labs(
    title = "ALL PARTICIPANTS: Histogram with Facet Wrap",
    x = "Value",
    y = "Frequency"
  )
hist_sensordays

boxplot_sensordays <- ggplot(sensor_all, aes(y = n_sensordays)) +
  geom_boxplot(fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~quarter*Year, ncol = 2) +
  theme_minimal() +
  labs(
    title = "ALL PARTICIPANTS: Boxpolot with Facet Wrap"
  )
boxplot_sensordays


# make wide data
sensor_all_wide <- pivot_wider(sensor_all, names_from = key, values_from = c(n_sensordays, mean, sd, se, median, IQR))
print(sensor_all_wide)
colnames(sensor_all_wide)

#export csv
write.csv(as.data.frame(sensor_all_wide), paste0(dir, "/data/clean_data/", "sensor_all_wide", ".csv"))
  

data_removed_summary <- clean_sensor_2018_2019_BL_Q1_Q2_Q3_Q4 %>%
  # select(-step, -sleep, -actmin) %>% 
  # filter(!quarter == "BL") %>% 
  filter(!quarter == "BL") %>% # exclude BL data
  mutate(remove_nosensor = ifelse(step == 0 & sleep == 0, "Yes", "No")) %>% 
  gather(key, value, -UserID, -quarter, -Year, -remove_nosensor,  -date)%>%
  group_by(UserID, Year, quarter, remove_nosensor) %>% 
  reframe(n=n(), 
          mean = round(mean(value), digits = 1, na.rm = TRUE),
          sd = round(sd(value), digits = 1), 
          se = round(sd(value)/sqrt(length(value)), digits = 1), 
          median = round(median(value), digits = 1), 
          IQR = round(IQR(value), digits = 1))) 
  # filter(remove_nosensor == "Yes")          
          
 
```


```{r eda, include=FALSE, echo=FALSE}

# get clean data from Alex
clean_all_data <- read.csv(paste0(dir, "/data/", "clean_data/sensor_selfreported_clean.csv"), header = TRUE)
clean_all_data$ssrs_wish <- as.factor(clean_all_data$ssrs_wish)
clean_all_data <- clean_all_data %>%
  filter(Year == 2018)


# suicide ideation: ssrs_wish
bar_ssrs_wish <- ggplot(clean_all_data, aes(x = as.factor(as.integer(ssrs_wish)), fill = ssrs_wish)) +
  geom_bar(stat = "count", position = "dodge") + # Use stat = "identity" for bar plots with y-values
  facet_wrap(~Year*quarter, ncol = 4) + # Correct the facet formula
  theme_minimal() +
  labs(
    title = "Bar Graph of Suicide Ideation",
    x = "Suicide Ideation", # Add a label for the x-axis
    y = "count" # Add a label for the y-axis
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  scale_x_discrete(
    labels = c(
      "1" = "Yes",
      "2" = "No")) + 
  scale_fill_manual(
    values = c("1" = "brown3", "2" = "cornflowerblue", "NA" = "grey"), # Set custom colors
    labels = c("Yes", "No", NA)                # Adjust legend labels
  )
bar_ssrs_wish

ggsave("bar_ssrs_wish_plot.png", plot = bar_ssrs_wish,width = 20, dpi = 300)


# suicide ideation: ssrs_wish
bar_ssrs_wish <- ggplot(clean_all_data, aes(x = as.factor(as.integer(ssrs_wish)), fill = ssrs_wish)) +
  geom_bar(stat = "fill") + # Use stat = "identity" for bar plots with y-values
  facet_wrap(~Year*quarter, ncol = 4) + # Correct the facet formula
  theme_minimal() +
  labs(
    title = "Bar Graph of Suicide Ideation",
    x = "Suicide Ideation", # Add a label for the x-axis
    y = "count" # Add a label for the y-axis
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  scale_x_discrete(
    labels = c(
      "1" = "Yes",
      "2" = "No")) + 
  scale_fill_manual(
    values = c("1" = "brown3", "2" = "cornflowerblue", "NA" = "grey"), # Set custom colors
    labels = c("Yes", "No", NA)                # Adjust legend labels
  )
bar_ssrs_wish

ggsave("bar_ssrs_wish_plot.png", plot = bar_ssrs_wish,width = 20, dpi = 300)


# has child
bar_ssrs_wish_child <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(x = as.factor(Child), fill = as.factor(ssrs_wish))) +
  geom_bar(stat = "count", position = "dodge") + 
  facet_wrap(~Year*quarter, ncol = 4) + # Correct the facet formula
  theme_minimal() +
  labs(
    x = "Has Child (Yes/No)",
    y = "count",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  scale_x_discrete(
    labels = c(
      "1" = "Yes",
      "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
bar_ssrs_wish_child

ggsave("bar_ssrs_wish_child_plot.png", plot = bar_ssrs_wish_child, width = 20, dpi = 300)


# # has child - boxplot
# boxplot_ssrs_wish_child <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(y = as.factor(Child), x = as.factor(ssrs_wish))) +
#   geom_boxplot() + 
#   facet_wrap(~Year*quarter, ncol = 4) + # Correct the facet formula
#   theme_minimal() +
#   labs(
#     x = "Has Child (Yes/No)",
#     y = "Proportion",
#     fill = "Suicide Ideation",
#   ) + 
#   theme_bw()+ 
#   theme(
#       plot.title = element_text(face = "bold", size = 30),
#       panel.background = element_rect(fill = "transparent"), # bg of the panel
#       plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
#       panel.grid.major = element_blank(), # get rid of major grid
#       panel.grid.minor = element_blank(), # get rid of minor grid
#       legend.title = element_blank(),
#       legend.text = element_text(face = "bold", size = 20),
#       legend.background = element_rect(fill = "transparent"), # get rid of legend bg
#       legend.box.background = element_blank(), # get rid of legend panel bg
#       axis.line = element_line(color="black", size=0.5),
#       axis.title.x = element_text(face="bold", size=20), 
#       axis.text.x = element_text(size=20, face = "bold", color = "black"),
#       axis.title.y = element_text(face="bold", size=20), 
#       axis.text.y = element_text(size=20, face = "bold", color = "black"),
#       strip.text = element_text(size = 20) # Adjust 'size' to increase label size
# ) + 
#   scale_x_discrete(
#     labels = c(
#       "1" = "Yes",
#       "0" = "No")) + 
#   scale_fill_manual(
#     values = c("brown3", "cornflowerblue", "grey"),
#     labels = c("Yes SI","No SI", "NA")
#   )
# boxplot_ssrs_wish_child


# clean_all_data$PHQtot
# PhQtot
hist_ssrs_wish_phqtot <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(fill = as.factor(ssrs_wish), x = PHQtot)) +
  geom_histogram(position = "dodge", bins = 30) +  # Replace geom_bar with geom_histogram and set bins
  facet_wrap(~Year*quarter, ncol = 4) +  
  theme_minimal() +
  labs(
    # x = "Frequency",
    x = "Depression Severity (PHQ-9 score)",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  # scale_x_discrete(
  #   labels = c(
  #     "1" = "Yes",
  #     "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
hist_ssrs_wish_phqtot

ggsave("hist_ssrs_wish_phqtot.png", plot = hist_ssrs_wish_phqtot,width = 20, dpi = 300)

# clean_all_data$daysoff

# Work Hours
hist_ssrs_wish_daysoff <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(fill = as.factor(ssrs_wish), x = daysoff)) +
  geom_histogram(position = "dodge", bins = 30) +  # Replace geom_bar with geom_histogram and set bins
  facet_wrap(~Year*quarter, ncol = 4) +  
  theme_minimal() +
  labs(
    # x = "Frequency",
    x = "Days Off in the Past Month",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  # scale_x_discrete(
  #   labels = c(
  #     "1" = "Yes",
  #     "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
hist_ssrs_wish_daysoff

ggsave("hist_ssrs_wish_daysoff.png", plot = hist_ssrs_wish_daysoff, width=20, dpi = 300)


# Sensor: sleep, quarterly average
hist_ssrs_wish_sensorsleep <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(fill = as.factor(ssrs_wish), x = mean_sleep/60)) +
  geom_histogram(position = "dodge", bins = 30) +  # Replace geom_bar with geom_histogram and set bins
  facet_wrap(~Year*quarter, ncol = 4) +  
  theme_minimal() +
  labs(
    # x = "Frequency",
    x = "Average, Sensor-based Sleep Duration (hours)",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  # scale_x_discrete(
  #   labels = c(
  #     "1" = "Yes",
  #     "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
hist_ssrs_wish_sensorsleep

ggsave("hist_ssrs_wish_sensorsleep.png", plot = hist_ssrs_wish_sensorsleep, width = 20, dpi = 300)


max(clean_all_data$sleepAve[!is.na(clean_all_data$sleepAve)])

# Sensor: sleep, quarterly average
hist_ssrs_wish_reportedsleep <- ggplot(subset(clean_all_data, !is.na(ssrs_wish) & sleepAve <20), aes(fill = as.factor(ssrs_wish), x = sleepAve)) +
  geom_histogram(position = "dodge") +  # Replace geom_bar with geom_histogram and set bins
  facet_wrap(~Year*quarter, ncol = 4) +  
  theme_minimal() +
  labs(
    # x = "Frequency",
    x = "Average, Self-Reported Avg. Sleep Duration (hours)",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  # scale_x_discrete(
  #   labels = c(
  #     "1" = "Yes",
  #     "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
hist_ssrs_wish_reportedsleep

ggsave("hist_ssrs_wish_reportedsleep.png", plot = hist_ssrs_wish_reportedsleep, width = 20, dpi = 300)




# mood rating, quarterly average
hist_ssrs_wish_mood <- ggplot(subset(clean_all_data, !is.na(ssrs_wish)), aes(fill = as.factor(ssrs_wish), x = mean_mood)) +
  geom_histogram(position = "dodge", bins = 30) +  # Replace geom_bar with geom_histogram and set bins
  facet_wrap(~Year*quarter, ncol = 4) +  
  theme_minimal() +
  labs(
    # x = "Frequency",
    x = "Average Daily Mood Rating",
    fill = "Suicide Ideation",
  ) + 
  theme_bw()+ 
  theme(
      plot.title = element_text(face = "bold", size = 30),
      panel.background = element_rect(fill = "transparent"), # bg of the panel
      plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
      panel.grid.major = element_blank(), # get rid of major grid
      panel.grid.minor = element_blank(), # get rid of minor grid
      legend.title = element_blank(),
      legend.text = element_text(face = "bold", size = 20),
      legend.background = element_rect(fill = "transparent"), # get rid of legend bg
      legend.box.background = element_blank(), # get rid of legend panel bg
      axis.line = element_line(color="black", size=0.5),
      axis.title.x = element_text(face="bold", size=20), 
      axis.text.x = element_text(size=20, face = "bold", color = "black"),
      axis.title.y = element_text(face="bold", size=20), 
      axis.text.y = element_text(size=20, face = "bold", color = "black"),
      strip.text = element_text(size = 20) # Adjust 'size' to increase label size
) + 
  # scale_x_discrete(
  #   labels = c(
  #     "1" = "Yes",
  #     "0" = "No")) + 
  scale_fill_manual(
    values = c("brown3", "cornflowerblue", "grey"),
    labels = c("Yes SI","No SI", "NA")
  )
hist_ssrs_wish_mood

ggsave("hist_ssrs_wish_mood.png", plot = hist_ssrs_wish_mood, width = 20, dpi = 300)



clean_all_data$PHQtot


view(clean_all_data)

```